import {
  Home,
  Car,
  Plane,
  ShoppingBag,
  Heart,
  GraduationCap,
  FileText,
  Briefcase,
  DollarSign,
  ChartLine,
  Gift,
  Utensils,
  Coffee,
  Shirt,
  Smartphone,
  Gamepad2,
  Music,
  Camera,
  Wrench,
  Zap,
  Wifi,
  Tv,
  Baby,
  Stethoscope,
  Pill,
  BookOpen,
  School,
  Palette,
  Dumbbell,
  Fuel,
  Train,
  Bus,
  Bike,
  Building,
  Building2,
  Store,
  Banknote,
  CreditCard,
  PiggyBank,
  Calculator,
  TrendingUp,
  TrendingDown,
  Receipt,
  Wallet,
  Coins,
  Crown,
  Star,
  Sparkles,
  Flower,
  Sun,
  Moon,
  Cloud,
  Shield,
  Lock,
  Key,
  Settings,
  Lightbulb,
  Battery,
  Users,
  User,
  Users2,
  ShoppingCart,
  Package,
  Truck,
  MapPin,
  Navigation,
  Compass,
  Mountain,
  Waves,
  Eye,
  Search,
  Filter,
  Grid3x3,
  List,
  Plus,
  Minus,
  X,
  Check,
  AlertCircle,
  Info,
  HelpCircle,
  Clock,
  Calendar,
  Bell,
  Mail,
  MessageCircle,
  Phone,
  PhoneCall,
  Video,
  Image,
  File,
  Edit,
  Trash2,
  Save,
  Send,
  Share,
  Bookmark,
  Flag,
  Pin,
  Map,
  Globe,
  Monitor,
  Laptop,
  Tablet,
  Watch,
  Headphones,
  Speaker,
  Volume2,
  Play,
  Pause,
  Music as MusicIcon,
  Gamepad,
  Trophy,
  Medal,
  Award,
  Target,
  Scissors,
  Circle,
  Square,
  Triangle,
  Diamond,
} from "lucide-react";

const iconMap: Record<string, React.ComponentType<{ className?: string }>> = {
  home: Home,
  car: Car,
  plane: Plane,
  "shopping-bag": ShoppingBag,
  heart: Heart,
  "graduation-cap": GraduationCap,
  "file-text": FileText,
  briefcase: Briefcase,
  "dollar-sign": DollarSign,
  "chart-line": ChartLine,
  gift: Gift,
  utensils: Utensils,
  coffee: Coffee,
  shirt: Shirt,
  smartphone: Smartphone,
  gamepad2: Gamepad2,
  music: Music,
  camera: Camera,
  wrench: Wrench,
  zap: Zap,
  wifi: Wifi,
  tv: Tv,
  baby: Baby,
  stethoscope: Stethoscope,
  pill: Pill,
  "book-open": BookOpen,
  school: School,
  palette: Palette,
  dumbbell: Dumbbell,
  fuel: Fuel,
  train: Train,
  bus: Bus,
  bike: Bike,
  building: Building,
  building2: Building2,
  store: Store,
  banknote: Banknote,
  "credit-card": CreditCard,
  "piggy-bank": PiggyBank,
  calculator: Calculator,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  receipt: Receipt,
  wallet: Wallet,
  coins: Coins,
  crown: Crown,
  star: Star,
  sparkles: Sparkles,
  flower: Flower,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  shield: Shield,
  lock: Lock,
  key: Key,
  settings: Settings,
  lightbulb: Lightbulb,
  battery: Battery,
  users: Users,
  user: User,
  users2: Users2,
  "shopping-cart": ShoppingCart,
  package: Package,
  truck: Truck,
  "map-pin": MapPin,
  navigation: Navigation,
  compass: Compass,
  mountain: Mountain,
  waves: Waves,
  eye: Eye,
  search: Search,
  filter: Filter,
  "grid-3x3": Grid3x3,
  list: List,
  plus: Plus,
  minus: Minus,
  x: X,
  check: Check,
  "alert-circle": AlertCircle,
  info: Info,
  "help-circle": HelpCircle,
  clock: Clock,
  calendar: Calendar,
  bell: Bell,
  mail: Mail,
  "message-circle": MessageCircle,
  phone: Phone,
  "phone-call": PhoneCall,
  video: Video,
  image: Image,
  file: File,
  edit: Edit,
  "trash-2": Trash2,
  save: Save,
  send: Send,
  share: Share,
  bookmark: Bookmark,
  flag: Flag,
  pin: Pin,
  map: Map,
  globe: Globe,
  monitor: Monitor,
  laptop: Laptop,
  tablet: Tablet,
  watch: Watch,
  headphones: Headphones,
  speaker: Speaker,
  "volume-2": Volume2,
  play: Play,
  pause: Pause,
  gamepad: Gamepad,
  trophy: Trophy,
  medal: Medal,
  award: Award,
  target: Target,
  scissors: Scissors,
  circle: Circle,
  square: Square,
  triangle: Triangle,
  diamond: Diamond,
};

interface IconRendererProps {
  iconName: string | null;
  className?: string;
  fallbackIcon?: React.ComponentType<{ className?: string }>;
}

export function IconRenderer({ iconName, className = "h-5 w-5", fallbackIcon: FallbackIcon }: IconRendererProps) {
  if (!iconName) {
    return FallbackIcon ? <FallbackIcon className={className} /> : <div className={`${className} rounded border border-dashed`} />;
  }

  const IconComponent = iconMap[iconName];
  if (!IconComponent) {
    return FallbackIcon ? <FallbackIcon className={className} /> : <div className={`${className} rounded border border-dashed`} />;
  }

  return <IconComponent className={className} />;
}
